### ISSUE TITLE
Chinese language support for readme documentation

### ISSUE THREAD

**Issue by weykon** [poteat/hkt-toolbelt#1]
Hi, I recently want a post I writing about HKT,  and your work is perfect.

**Comment by weykon** [comment]
I'm learning you repo now

**Comment by weykon** [comment]
[this my code about HKT for practice](https://github.com/weykon/typescript_study/tree/main/%E7%B1%BB%E5%9E%8B%E7%B3%BB%E7%BB%9F/HKT)
could I join you for something if I can do

**Comment by poteat** [comment]
Yeah, I am very amenable to your translating a Chinese version!

**Comment by poteat** [comment]
@weykon I've added a translations section, as well as a template for you (or another person) to fill out at some point.

<img width="1294" alt="image" src="https://user-images.githubusercontent.com/7668446/198231407-f1d46596-78b6-4fb3-9fa2-56f6a03144cd.png">

**Comment by poteat** [comment]
<img width="1586" alt="image" src="https://user-images.githubusercontent.com/7668446/198231639-60099070-0303-4be7-ab87-9a0a008f27bc.png">

**Comment by weykon** [comment]
Oh, Thanks!

**Comment by poteat** [comment]
Feel free to make a pull request to fill out the template with real Chinese :)

**Comment by poteat** [comment]
Closing per #2, thanks again :)
