### ISSUE TITLE
Include Breaking changes 0.19.0 in documentation 

### ISSUE THREAD

**Issue by nicobrinkkemper** [poteat/hkt-toolbelt#18]
Scrolling through the documentation I can see a number of functions that don't work as described, for example `List.Map`. I'm also not convinced more `$<>` makes the code cleaner, but I know that's a different story and up to the author. The fact is, the documentation is different from how this library should be consumed now. 

Another thing I've noticed is that `Kind` imported from `hkt-toolbelt` is different from `Kind` imported from `hkt-toolbelt/kind`, have to switch imports to `/kind` where I've used the latter before. 
 ```ts
 import type { Kind, _ } from "hkt-toolbelt/kind";
```
I've seen the novel usage of ChatGTP to refactor the codebase. Very cool, maybe it could also be prompted to update the documentation and perhaps write a migration guide for humans?

**Comment by MajorLift** [comment]
Hi, sorry it took so long to respond. You're absolutely right that the API docs section of the README is heavily outdated. We've been working on setting up a workflow for using JSDoc comments (written with the help of AI) to auto-generate up-to-date documentation.

We've finally made enough progress with that to deploy a demo static site: https://majorlift.github.io/hkt-toolbelt. 

The official documentation will use a different url, but this demo site should be good enough to use as a reference for the time being, and get a sense of where we're headed in terms of documentation.
