### ISSUE TITLE
Is this a mistake?

### ISSUE THREAD

**Issue by Jvp2001** [poteat/hkt-toolbelt#28]
I have only started type level programming fairly recently; I was wondering if the FilterNum example in the readme file is missing the **infer** keywords before **Head** and **Tail**. 
<img width="753" alt="image" src="https://github.com/poteat/hkt-toolbelt/assets/14146913/f705e7e5-8614-4cd3-aee0-99561738c7e3">

**Comment by Jvp2001** [comment]
I made a pull request.

**Comment by poteat** [comment]
Thanks so much! Merged.
