### ISSUE TITLE
Confusing term "full Kinds" in readme

### ISSUE THREAD

**Issue by gaac510** [poteat/hkt-toolbelt#4]
Translating the rest of the readme to Chinese at the moment. What is `(e.g. full Kinds)` in the below line referring to?

https://github.com/poteat/hkt-toolbelt/blob/b50061014857a564a003fa25a50c3da036ef45a6/readme.md?plain=1#L215

**Comment by poteat** [comment]
I agree that it's not very clear. Here by 'full Kind', I mean a class that extends the abstract type `Kind`, i.e. is capable of being applied using `$`.

**Comment by poteat** [comment]
Closed by Closed by https://github.com/poteat/hkt-toolbelt/commit/c077c0b335698f04b03401b04859c6eedba91dc2 ✅
