### ISSUE TITLE
Confusing term "syntho-recursive" in readme

### ISSUE THREAD

**Issue by gaac510** [poteat/hkt-toolbelt#5]
Googled it and this readme is literally the only returned result.
https://github.com/poteat/hkt-toolbelt/blob/b50061014857a564a003fa25a50c3da036ef45a6/readme.md?plain=1#L300

Wouldn't have anything to do with this, would it?
https://www.urbandictionary.com/define.php?term=Syntho

**Comment by poteat** [comment]
@gaac510 I suppose it would've been better described as a "synthetically recursive" kind. In that we are implementing a recursive higher-order-type that _does not_ directly reference itself from the perspective of the compiler. You could describe the eponynmous Y combinator as creating 'synthetic' recursion as compared to methods built-in to the language.

**Comment by poteat** [comment]
Closed by https://github.com/poteat/hkt-toolbelt/commit/c077c0b335698f04b03401b04859c6eedba91dc2 ✅
