### ISSUE TITLE
What is the state of the main documentation?

### ISSUE THREAD

**Issue by ric-rai** [poteat/hkt-toolbelt#63]
Hello, you have an awesome library here. It has already been helping me to type some functions properly finally. Although, I've noticed that the documentation is not up to date. Do you need help with it? More precisely, what bothers me is that in the documentation, many of the types are generic, although, in reality, they need to be applied with the dollar type.

**Comment by MajorLift** [comment]
Thanks for using hkt-toolbelt! For now, you should refer to the jsdoc comments for explanations and examples regarding our features, as the API docs section of the README is very much out of date. 

We're looking into setting up a typedoc github workflow to automate publishing documentation, and have been working on overhauling the jsdoc comments for this. 

We'd definitely appreciate any help or suggestions you might be able to provide.

**Comment by MajorLift** [comment]
@ric-rai I deployed a demo static site hosting documentation that's auto-generated based on our JSDoc comments: https://majorlift.github.io/hkt-toolbelt.

We'll be using a different url for the official documentation, but this demo site should be good enough to use as a reference for the time being, and get a sense of where we're headed in terms of documentation. 

We still have a few modules that haven't been documented with JSDoc (see https://github.com/poteat/hkt-toolbelt/issues/52). Contributions on those would be very welcome from anyone.
